//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lakopark.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lakopark.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap balnyil {
            get {
                object obj = ResourceManager.GetObject("balnyil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Haz1 {
            get {
                object obj = ResourceManager.GetObject("Haz1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Haz2 {
            get {
                object obj = ResourceManager.GetObject("Haz2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Haz3 {
            get {
                object obj = ResourceManager.GetObject("Haz3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jobbnyil {
            get {
                object obj = ResourceManager.GetObject("jobbnyil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kereszt {
            get {
                object obj = ResourceManager.GetObject("kereszt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puskás Ferenc
        ///5;10
        ///1;1;2
        ///1;2;1
        ///1;3;1
        ///1;6;3
        ///1;7;1
        ///2;2;1
        ///2;3;2
        ///2;6;2
        ///2;8;2
        ///3;2;1
        ///3;3;3
        ///3;4;1
        ///3;5;3
        ///3;6;2
        ///3;7;1
        ///3;8;1
        ///4;3;2
        ///4;5;3
        ///4;6;2
        ///4;8;3
        ///4;9;3
        ///5;1;1
        ///5;4;1
        ///5;7;1
        ///5;8;3
        ///
        ///Van Gogh
        ///3;5
        ///1;1;1
        ///1;3;3
        ///1;5;2
        ///2;1;3
        ///2;3;3
        ///2;4;3
        ///2;5;2
        ///3;1;1
        ///3;2;3
        ///3;5;2
        ///
        ///Vivaldi
        ///4;7
        ///1;2;3
        ///1;3;1
        ///1;7;3
        ///2;1;2
        ///2;2;2
        ///2;3;3
        ///2;7;2
        ///3;2;1
        ///3;5;1
        ///3;6;1
        ///3;7;3
        ///4;1;2
        ///4;2;3
        ///4;3;2
        ///4;5;3
        ///4;6;3
        ///
        ///.
        /// </summary>
        internal static string lakoparkok {
            get {
                return ResourceManager.GetString("lakoparkok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Puskás_Ferenc {
            get {
                object obj = ResourceManager.GetObject("Puskás_Ferenc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Van_Gogh {
            get {
                object obj = ResourceManager.GetObject("Van_Gogh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vivaldi {
            get {
                object obj = ResourceManager.GetObject("Vivaldi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
